Routing branch
kan15/words-app pull request #6
Opened 2021-12-06 20:03 UTC by kan15

2021-12-06 21:32 UTC, zem-aleks requested changes

2021-12-06 21:32 UTC, zem-aleks commented on src/components/EditableWord.tsx
> +  setEditableWord: (word: null | Word) => void;
это еще с прошлого реквеста осталось. Ребенок ставит родителю выбранный элемент, а должен просто говорить что нажали cancel и родитель ставить выбранный элемент в null

2021-12-06 21:32 UTC, zem-aleks commented on src/components/WordItem.tsx
> +            setEditableWord(word);
таже проблема с setEditableWord - ребенок просто говорит что его клацнули меседж и word посылаем родителю, он сетит список в нужный стейт

2021-12-06 21:32 UTC, zem-aleks commented on src/components/WordsList.tsx
> +  const [editableWord, setEditableWord] = useState<null | Word>(null);
я вот чет задумался, а зачем вообще делать стейт на этом уровне? 

Сделай компоненту общую для  компонента айтема со своим стейтом. В стейте переключай вид с EditableWord на WordItem. Можно будет сразу несколько слов редактировать и общего стейта у списка не будет

2021-12-06 21:32 UTC, zem-aleks commented on src/components/learning/LearningForm.tsx
> +  label: Languages | string;
странный тип. Почему | string?

2021-12-06 21:46 UTC, zem-aleks requested changes

2021-12-06 21:46 UTC, zem-aleks commented on src/components/learning/LearningForm.tsx
> +    setTypeStudy(event.target.value);
такие вещи можно сразу писать внутрь JSX. Не придется еще и типы дописывать

2021-12-06 21:46 UTC, zem-aleks commented on src/components/learning/LearningForm.tsx
> +  const handleSubmit = () => {
лишняя функция. Можно прям в JSX это написать

2021-12-06 21:46 UTC, zem-aleks commented on src/components/learning/LearningPageLoader.tsx
> +      type: "getting_user_data";
выбери один стиль меседжей. У тебя то camelCase, to snake_case, то где-то СamelCase был кажется. Не суть какой, но юзай везде одинаковый стиль

2021-12-06 21:46 UTC, zem-aleks commented on src/components/learning/LearningPageLoader.tsx
> +  const [stateLearningWords, setStateLearningWords] =
потенциальная проблема в разделение этих двух стейтов. У тебя получиться размерность(stateLearning) * размерность(stateLearningWords) возможных стейтов в приложении. Здесь нужно подумать как должны ли эти стейты быть в одной компоненте или можно их раскинуть по разным. Или их нужно совместить в в один стейт.

2021-12-06 21:46 UTC, zem-aleks commented on src/components/learning/LearningPageLoader.tsx
> +  show: string;
подозрительный тип. Выглядит как-будто он содержит в себе и данные и части интерфейса.

2021-12-08 20:31 UTC, kan15 commented on src/components/EditableWord.tsx
> +  setEditableWord: (word: null | Word) => void;
Исправил

2021-12-08 20:31 UTC, kan15 commented on src/components/WordItem.tsx
> +            setEditableWord(word);
Исправил

2021-12-08 20:31 UTC, kan15 commented on src/components/WordsList.tsx
> +  const [editableWord, setEditableWord] = useState<null | Word>(null);
Сделал одну компоненту. Теперь внутри этой компоненты определяется что именно показывать.

2021-12-08 20:32 UTC, kan15 commented on src/components/learning/LearningForm.tsx
> +  label: Languages | string;
Нужна твоя помощь. Я не знаю почему, но без string, у меня не работает оно.

2021-12-08 20:32 UTC, kan15 commented on src/components/learning/LearningForm.tsx
> +    setTypeStudy(event.target.value);
Исправил.

2021-12-08 20:32 UTC, kan15 commented on src/components/learning/LearningForm.tsx
> +  const handleSubmit = () => {
Я сделал отдельную функцию так как у меня эта функция висит и на форме и на кнопке. Или если она висит уже на форме, но тогда на кнопку submit ее можно не добавлять?

2021-12-08 20:32 UTC, kan15 commented on src/components/learning/LearningPageLoader.tsx
> +      type: "getting_user_data";
У меня то, что касается месседжей в CamelCase, то что касается state - snake_case. Ты мне первый раз так их сделал, я теперь так и делаю. Если и одно и другое должно быть в одном стиле - я переделаю.

2021-12-08 20:32 UTC, kan15 commented on src/components/learning/LearningPageLoader.tsx
> +type StateLearningWords = [] | LearningWord[];
Не совсем понял вопроса. Я этим хочу сказать, что у меня этот state или пустой массив или массив из объектов LearningWord

2021-12-08 20:33 UTC, kan15 commented on src/components/learning/LearningPageLoader.tsx
> +  const [stateLearningWords, setStateLearningWords] =
Извини, не совсем понял каких изменений требует этот комментарий. Можешь пожалуйста еще объяснить что мне нужно сделать и в чем проблема.

2021-12-08 20:33 UTC, kan15 commented on src/components/learning/LearningPageLoader.tsx
> +  show: string;
Тут имеется в виду какую часть слова (eng или rus) мы показываем, а какую скрываем. Т.е. open здесь - это открытая часть, ту, что показываем юзеру.
Но даже если это содержит часть интерфейса, это проблема? Можешь дать что-то почитать пожалуйста по этой теме?
У меня дальнейшая идея это добавить дополнительное свойство в этот объект 
null | boolean
 и когда произойдет проверка слова присваивать значение true или false, а потом отталкиваясь от этого менять цвет слова в табличке. Так делать нельзя получается?

2021-12-08 21:19 UTC, zem-aleks commented on src/components/learning/LearningPageLoader.tsx
> +type StateLearningWords = [] | LearningWord[];
пустой массив - это не тип, это значение массива. 

LearningWord[] - может быть и пустым массивом и не пустым - это тип который говорит что у тебя будет массив слов

[] - это реальный массив, это не тип

2021-12-08 21:19 UTC, zem-aleks commented on src/components/learning/LearningPageLoader.tsx
> +type StateLearningWords = [] | LearningWord[];
удали этот тип. Он избыточный. 
Это все равно что прописать типы для массива строк или числе
type Strings = string[];  -так обычно не делают

2021-12-08 21:19 UTC, zem-aleks commented on src/components/learning/LearningPageLoader.tsx
> +  const [stateLearningWords, setStateLearningWords] =
здесь маркер проблемы что у тебя 2 стейта в одном месте. Мне сложно будет обьяснить, потому что эта компонента имеет несколько назначений и мне ее трудно прочитать. 

Я бы сделал следующим образом, закончи свою логику. Сделай чтобы работало как тебе нужно. А после мы возьмем уже работающее приложение как основу и где-то рядом напишем implementation plan. Нужно научится проектировать приложение до его иплементации

2021-12-13 20:02 UTC, merged